## Criação e Manipulação de Arrays NumPy

In [4]:
# biblioteca NumPy

# testes sem NumPy
# criar sequencia python
python_list = [i for i in range(1_000_000 + 1)]

## Tempo de execução: 0.107s
## Memória utilizada: 39.8 MiB

In [5]:
# pip3 install numpy

In [3]:
import numpy as np

In [7]:
# criar sequencia numpy
numpy_array = np.arange(0, 1_000_000 + 1, dtype='int64')

## Tempo de execução: 0.08s
## Memória utilizada: 7.5MiB

In [8]:
# calcular quadrados python
python_list_square = [i**2 for i in python_list]

## Tempo de execução: 0.520s
## Memória utilizada: 38.4MiB

# calcular quadrados numpy
numpy_array_square = numpy_array**2

## Tempo de execução: 0.005s
## Memória utilizada: 7.6MiB

## Tipo e Acesso aos Elementos de um Array

In [9]:
# criando um array
arr = np.array([1,2,3,4,5])
print(f'Elementos: {arr}, Tipo dos elementos: {arr.dtype}, Tamanho do array: {arr.shape}')

Elementos: [1 2 3 4 5], Tipo dos elementos: int64, Tamanho do array: (5,)


In [10]:
# acesso ao terceiro elemento do array (índice 2):
elemento = arr[2]
print(elemento)

3


In [11]:
# obtendo elementos de índice 1 a 3:
subset = arr[1:4]
print(subset)

[2 3 4]


In [16]:
# criando uma matriz
matrix = np.arange(1., 10.).reshape((3,3))
print(matrix)
print(f'Tipo dos elementos: {matrix.dtype}, Dimensões da matriz: {matrix.shape}')

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Tipo dos elementos: float64, Dimensões da matriz: (3, 3)


In [17]:
## acessando a linha 2
linha = matrix[1]
print(linha)

## acessando a 1 coluna
coluna = matrix[:,0]
print(coluna)

[4. 5. 6.]
[1. 4. 7.]


In [18]:
## multiplicar todos os elementos por 2
a = np.array([1.0, 2.0, 3.0])
b = 2.0

resultado = a * b
print(resultado)

[2. 4. 6.]


## Multiplicação de Matrizes

In [25]:
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[1], [2]])

In [26]:
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [27]:
print(B)

[[1]
 [2]]


In [29]:
## Multiplicação utilizando apenas listas Python
C = [[0], [0], [0]]

for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            C[i][j] += A[i][k] * B[k][j]

print(C)

[[np.int64(5)], [np.int64(11)], [np.int64(17)]]


In [30]:
## agora vamos realizar a mesma operação com Numpy
D = A @ B
print(D)

[[ 5]
 [11]
 [17]]


In [38]:
## agora vamos multiplicar uma matriz gigante com Numpy
N = 500
A = np.arange(N*N, dtype='int64').reshape(N,N)
B = A * 2

C = A @ B
print(C)

## Tempo de execução: 0.196s
## Memória utilizada: 5.8MiB

[[   41541750000    41541999500    41542249000 ...    41665751500
     41666001000    41666250500]
 [  103916750000   103917499500   103918249000 ...   104289251500
    104290001000   104290750500]
 [  166291750000   166292999500   166294249000 ...   166912751500
    166914001000   166915250500]
 ...
 [31041916750000 31042165499500 31042414249000 ... 31165545251500
  31165794001000 31166042750500]
 [31104291750000 31104540999500 31104790249000 ... 31228168751500
  31228418001000 31228667250500]
 [31166666750000 31166916499500 31167166249000 ... 31290792251500
  31291042001000 31291291750500]]


In [39]:
## agora vamos multiplicar uma matriz com python
A_list = A.tolist()
B_list = B.tolist()
C_list = np.zeros_like(A).tolist()

for i in range(len(A_list)):
    for j in range(len(B_list[0])):
        for k in range(len(B_list)):
            C_list[i][j] += A_list[i][k] * B_list[k][j]

print(C_list)
## Tempo de execução: 66.462s
## Memória utilizada: 211.6MiB

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [1]:
## exercícios

In [4]:
A = np.array([
    [" ", " ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " ", " "]
])

for i in range(6):
    A[i][i] = "#"

print(A)

[['#' ' ' ' ' ' ' ' ' ' ']
 [' ' '#' ' ' ' ' ' ' ' ']
 [' ' ' ' '#' ' ' ' ' ' ']
 [' ' ' ' ' ' '#' ' ' ' ']
 [' ' ' ' ' ' ' ' '#' ' ']
 [' ' ' ' ' ' ' ' ' ' '#']]


In [5]:
A = np.array([
    [" ", " ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " ", " "]
])

for i in range(6):
    for j in range(6):
        if(i<j):
            A[i][j] = "#"

print(A)

[[' ' '#' '#' '#' '#' '#']
 [' ' ' ' '#' '#' '#' '#']
 [' ' ' ' ' ' '#' '#' '#']
 [' ' ' ' ' ' ' ' '#' '#']
 [' ' ' ' ' ' ' ' ' ' '#']
 [' ' ' ' ' ' ' ' ' ' ' ']]


In [6]:
A = np.array([
    [" ", " ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " ", " "]
])

for i in range(6):
    A[i][5 - i] = "#"

print(A)

[[' ' ' ' ' ' ' ' ' ' '#']
 [' ' ' ' ' ' ' ' '#' ' ']
 [' ' ' ' ' ' '#' ' ' ' ']
 [' ' ' ' '#' ' ' ' ' ' ']
 [' ' '#' ' ' ' ' ' ' ' ']
 ['#' ' ' ' ' ' ' ' ' ' ']]


In [7]:
A = np.array([
    [" ", " ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " ", " "],
    [" ", " ", " ", " ", " ", " "]
])

for i in range (6):
    for j in range (6):
        if(i>j):
            A[i][j] = "#"

print(A)

[[' ' ' ' ' ' ' ' ' ' ' ']
 ['#' ' ' ' ' ' ' ' ' ' ']
 ['#' '#' ' ' ' ' ' ' ' ']
 ['#' '#' '#' ' ' ' ' ' ']
 ['#' '#' '#' '#' ' ' ' ']
 ['#' '#' '#' '#' '#' ' ']]
